### PR TITLE
Add autosudo.sh for trackable sudoing

### PR DESCRIPTION
**Pull request by f3flight**
This script can be installed like so:
```
linux:
  system:
    profile:
      autosudo.sh: null
```

### CODE REVIEW

**Comment by cloudlab-autobuild** [comment]
Can one of the admins verify this patch?

**Comment by smolaon** [comment]
Please provide Readme. I would use model way to define this script. Not directly in formula.

**Comment by fpytloun** [comment]
I also don't think random scripts belong to formulas.

**Comment by f3flight** [comment]
moved into system model as a separate yaml file

**Pull request closed without merging**
