### PR TITLE
install system packages before adding new repo

### PR DESCRIPTION
**Pull request by Martin819**

### CODE REVIEW

**Comment by cloudlab-autobuild** [comment]
Can one of the admins verify this patch?

**Comment by fpytloun** [comment]
I think this was already fixed in some earlier pull request or not?

**Comment by Martin819** [comment]
I'm not sure, but probably not, because it wasn't working before this change. Until now, it added repo to sources.list and then tried to install packages, which caused "The method driver /usr/lib/apt/methods/https could not be found" if the added repo was 'https'.

**Comment by fpytloun** [comment]
https://github.com/salt-formulas/salt-formula-linux/pull/69

**Comment by Martin819** [comment]
PR #69 works fine, so I'm closing this one.

**Pull request closed without merging**
