### PR TITLE
[MMO-140] Add/ensure packages that are useful for troubleshooting

### PR DESCRIPTION
**Pull request by erickcantwell**
Add/ensure packages that are useful for debugging and troubleshooting.  These should be installed by default.

### CODE REVIEW

**Comment by cloudlab-autobuild** [comment]
Can one of the admins verify this patch?

**Comment by tomkukral** [comment]
I'd prefer don't have tools`'mcelog', 'smartmontools', 'lsscsi',` everywhere, for example in VMs.

**Comment by fpytloun** [comment]
No, if you need some extra packages, define them in your metadata model. salt-formula-linux should not ship packages that are not necessary for required functionality.

**Comment by erickcantwell** [comment]
tomkukral, that's an okay point, but they won't cause any harm by being there.

fpytloun, I don't agree with you.  Especially when there are packages like 'vim' listed under Arch, and wireless utilities listed under network packages.  When was the last time a server had a wireless nic in it, or ran Arch?  I guess we should get rid of telnet under the Redhat packages?  

Under other network packages we have things like this listed;
'bridge_pkgs': ['bridge-utils'],
        'ovs_pkgs': ['openvswitch-switch', 'bridge-utils'],
        'dpdk_pkgs': ['dpdk', 'dpdk-dev', 'dpdk-dkms', 'dpdk-igb-uio-dkms', 'dpdk-rte-kni-dkms'],

Clearly we made special cases in the formula for pieces that are not required by Linux to run.  Also, I would argue that the functionality that they provide is debugging and troubleshooting.  I think that's a pretty important part to running a cloud.

**Comment by fpytloun** [comment]
Unfortunately that's legacy and these packages should be removed from the list and installed only when needed.
Also Archlinux is only partly supported distribution.

**Pull request closed without merging**
