### PR TITLE
Introduce template option for linux.system.file

### PR DESCRIPTION
**Pull request by TheGOro**
Change-Id: Ifb45b2cf72d71caa9c8a63f8e7684fd15b81e450
Implements: jira/CLOUDB-487
Signed-off-by: Gabor Orosz <gabor.orosz@ericsson.com>

### CODE REVIEW

**Comment by alexz-kh** [comment]
+2

**Comment by epcim** [comment]
I would kindly ask you to add update tests as well: https://github.com/salt-formulas/salt-formula-linux/blob/master/tests/pillar/system_file.sls

Thanks

**Comment by TheGOro** [comment]
> 
> 
> I would kindly ask you to add update tests as well: https://github.com/salt-formulas/salt-formula-linux/blob/master/tests/pillar/system_file.sls
> 
> Thanks

I'm more than happy to do that, but I need some guidance regarding how to run the tests in an isolated way, that doesn't try to alter files and configurations on my system.
About the test itself. I haven't figured out how can I place example template files to the salt web server (salt://) with the current test framework. Placing files to arbitrary external web locations doesn't seem a good practice for me.

Best regards,
GOro

**Comment by epcim** [comment]
@TheGOro check this:
https://kitchen.saltstack.com/
https://salt-formulas.readthedocs.io/en/latest/develop/testing-formulas.html

**Comment by TheGOro** [comment]
> @TheGOro check this:
> https://kitchen.saltstack.com/
> https://salt-formulas.readthedocs.io/en/latest/develop/testing-formulas.html

@epcim
I have introduced a test case for this change as well. Can you please review it and give some feedback?

**Comment by alexz-kh** [comment]
Merged via https://github.com/salt-formulas/salt-formula-linux/commit/dd80ea394b62892d1fe828611a5218311297069d

**Comment by bbinet** [comment]
This can be closed since merged in dd80ea3

**Comment by prometheanfire** [comment]
please close

**Pull request closed without merging**
